name       : perl-class-method-modifiers
version    : 2.12
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Class-Method-Modifiers-2.12.tar.gz : e44c1073020bf55b8c97975ed77235fd7e2a6a56f29b5c702301721184e27ac8
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Class::Method::Modifiers - Provides Moose-like method modifiers
description: |
    Class::Method::Modifiers - Provides Moose-like method modifiers
builddeps  :
    - perl
rundeps    :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
