name       : perl-class-method-modifiers
version    : '2.15'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Class-Method-Modifiers-2.15.tar.gz : 65cd85bfe475d066e9186f7a8cc636070985b30b0ebb1cde8681cf062c2e15fc
homepage   : https://metacpan.org/pod/Class::Method::Modifiers
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Class::Method::Modifiers - Provides Moose-like method modifiers
description: |
    Class::Method::Modifiers - Provides Moose-like method modifiers
builddeps  :
    - perl
rundeps    :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
