name       : perl-class-method-modifiers
version    : '2.13'
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Class-Method-Modifiers-2.13.tar.gz : ab5807f71018a842de6b7a4826d6c1f24b8d5b09fcce5005a3309cf6ea40fd63
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Class::Method::Modifiers - Provides Moose-like method modifiers
description: |
    Class::Method::Modifiers - Provides Moose-like method modifiers
builddeps  :
    - perl
rundeps    :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
